# Generated by Django 3.2.11 on 2025-12-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_shop_order_payment'),
        ('myapp', '0046_shop_variants_inventory'),
    ]

    operations = [
    ]
