from django.urls import path

from myapp import views

app_name = 'myapp'
urlpatterns = [
    # 后台管理api
    path('admin/overview/count', views.admin.overview.count),
    path('admin/overview/dataCount', views.admin.overview.dataCount),
    path('admin/thing/list', views.admin.thing.list_api),
    path('admin/thing/detail', views.admin.thing.detail),
    path('admin/thing/create', views.admin.thing.create),
    path('admin/thing/update', views.admin.thing.update),
    path('admin/thing/quickUpdate', views.admin.thing.quick_update),
    path('admin/thing/batchUpdate', views.admin.thing.batch_update),
    path('admin/thing/delete', views.admin.thing.delete),
    path('admin/news/list', views.admin.news.list_api),
    path('admin/news/create', views.admin.news.create),
    path('admin/news/delete', views.admin.news.delete),
    path('admin/news/update', views.admin.news.update),
    path('admin/case/list', views.admin.case.list_api),
    path('admin/case/create', views.admin.case.create),
    path('admin/case/delete', views.admin.case.delete),
    path('admin/case/update', views.admin.case.update),
    path('admin/faq/list', views.admin.faq.list_api),
    path('admin/faq/create', views.admin.faq.create),
    path('admin/faq/delete', views.admin.faq.delete),
    path('admin/faq/update', views.admin.faq.update),
    path('admin/comment/list', views.admin.comment.list_api),
    path('admin/comment/create', views.admin.comment.create),
    path('admin/comment/delete', views.admin.comment.delete),
    path('admin/comment/update', views.admin.comment.update),
    path('admin/advantage/list', views.admin.advantage.list_api),
    path('admin/advantage/create', views.admin.advantage.create),
    path('admin/advantage/delete', views.admin.advantage.delete),
    path('admin/advantage/update', views.admin.advantage.update),
    path('admin/download/list', views.admin.download.list_api),
    path('admin/download/create', views.admin.download.create),
    path('admin/download/delete', views.admin.download.delete),
    path('admin/download/update', views.admin.download.update),
    path('admin/inquiry/list', views.admin.inquiry.list_api),
    path('admin/inquiry/create', views.admin.inquiry.create),
    path('admin/inquiry/delete', views.admin.inquiry.delete),
    path('admin/inquiry/update', views.admin.inquiry.update),
    path('admin/basicSite/list', views.admin.basicSite.list_api),
    path('admin/basicSite/update', views.admin.basicSite.update),
    path('admin/basicTdk/list', views.admin.basicTdk.list_api),
    path('admin/basicTdk/update', views.admin.basicTdk.update),
    path('admin/basicBanner/list', views.admin.basicBanner.list_api),
    path('admin/basicBanner/update', views.admin.basicBanner.update),
    path('admin/basicGlobal/listInfo', views.admin.basicGlobal.list_info),
    path('admin/basicGlobal/list', views.admin.basicGlobal.list_api),
    path('admin/basicGlobal/update', views.admin.basicGlobal.update),
    path('admin/basicAdditional/list', views.admin.basicAdditional.list_api),
    path('admin/basicAdditional/update', views.admin.basicAdditional.update),
    path('admin/about/list', views.admin.about.list_api),
    path('admin/about/update', views.admin.about.update),
    path('admin/cdn/uploadLogoImg', views.admin.cdn.upload_logo_img),
    path('admin/cdn/uploadIcoImg', views.admin.cdn.upload_ico_img),
    path('admin/cdn/uploadImg', views.admin.cdn.upload_img),
    path('admin/cdn/uploadNormalFile', views.admin.cdn.upload_normal_file),
    path('admin/cdn/uploadFile', views.admin.cdn.upload_file),
    path('admin/category/list', views.admin.category.list_api),
    path('admin/category/create', views.admin.category.create),
    path('admin/category/update', views.admin.category.update),
    path('admin/category/delete', views.admin.category.delete),
    path('admin/opLog/list', views.admin.opLog.list_api),
    path('admin/opLog/deleteAll', views.admin.opLog.deleteAll),
    path('admin/opLog/delete', views.admin.opLog.delete),
    path('admin/user/list', views.admin.user.list_api),
    path('admin/user/create', views.admin.user.create),
    path('admin/user/delete', views.admin.user.delete),
    path('admin/user/updatePwd', views.admin.user.updatePwd),
    path('admin/adminLogin', views.admin.user.admin_login),

    path('admin/order/list', views.admin.order.list_api),
    path('admin/order/detail', views.admin.order.detail),
    path('admin/order/updateStatus', views.admin.order.update_status),

    path('admin/payment/list', views.admin.payment.list_api),

    path('admin/shop/settings/get', views.admin.shop_settings.get_api),
    path('admin/shop/settings/update', views.admin.shop_settings.update_api),
    path('admin/shop/settings/testPayPal', views.admin.shop_settings.test_paypal),

    path('admin/media/list', views.admin.media.list_api),
    path('admin/media/delete', views.admin.media.delete_api),

    path('admin/i18n/list', views.admin.i18n.list_api),
    path('admin/i18n/upsert', views.admin.i18n.upsert),
    path('admin/i18n/delete', views.admin.i18n.delete),


    # 前台管理api
    path('index/thing/section', views.index.thing.section),
    path('index/thing/detail', views.index.thing.detail),
    path('index/common/section', views.index.common.section),
    path('index/inquiry/create', views.index.inquiry.create),
    path('index/contact/section', views.index.contact.section),
    path('index/about/section', views.index.about.section),
    path('index/faq/section', views.index.faq.section),
    path('index/download/section', views.index.download.section),
    path('index/case/section', views.index.case.section),
    path('index/case/detail', views.index.case.detail),
    path('index/news/section', views.index.news.section),
    path('index/news/detail', views.index.news.detail),
    path('index/home/section', views.index.home.section),
    path('index/sitemap/section', views.index.sitemap.section),

    # 电商（shop）
    path('shop/order/create', views.shop.order.create),
    path('shop/order/query', views.shop.order.query),
    path('shop/settings', views.shop.get_settings),
    path('shop/pay/stripe/createSession', views.shop.payment.stripe_create_session),
    path('shop/pay/stripe/confirm', views.shop.payment.stripe_confirm),
    path('shop/pay/stripe/webhook', views.shop.payment.stripe_webhook),
    path('shop/pay/paypal/createOrder', views.shop.payment.paypal_create_order),
    path('shop/pay/paypal/capture', views.shop.payment.paypal_capture),
]
